HW7 - done
RollerM0bster/hw-esheludenko pull request #10
Opened 2024-11-23 17:49 UTC by RollerM0bster

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-11-23 21:57 UTC, vladislavmass requested changes

2024-11-23 21:57 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Этой ошибке тут явно не  место. Лучше вернуть системную ошибку, так как  она позволит пользователю решить его проблему в отличие от этой ошибки

2024-11-24 15:02 UTC, RollerM0bster commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Поправила

2024-11-24 17:06 UTC, vladislavmass requested changes

2024-11-24 17:06 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	if fileSize == 0 {
В чем проблема скопировать файл размером 0 байт? Может это просто какой нибудь флаг.

2024-11-24 17:06 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Не нужно тут переопределять ошибку. Ошибка, которую вернет пользователь метод Stat даст возможность исправить ошибку, наша же ошибка в данном случае никакой смысловой нагрузки не несет

2024-11-24 17:15 UTC, RollerM0bster commented on hw07_file_copying/copy.go
> +		return ErrUnsupportedFile
Поправила

2024-11-24 18:17 UTC, vladislavmass approved these changes

2024-11-24 18:17 UTC, vladislavmass commented on hw07_file_copying/copy.go
> +	defer file.Close()
Эту строчку правильнее поставить сразу после открытия.

2024-11-24 18:46 UTC, merged